name: Weekly Post Generator

on:
  schedule:
    - cron: '0 12 * * 1'  # Runs every Monday at 12:00 UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-post:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Weekly-Post repo
      uses: actions/checkout@v4
      with:
        repository: clintjb/Weekly-Post
        path: Weekly-Post

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd Weekly-Post
        pip install -r requirements.txt
        pip install requests beautifulsoup4 pillow python-markdown

    - name: Run article.py to grab the Hacker News post
      run: |
        cd Weekly-Post
        python article.py

    - name: Run generate.py to generate the Jekyll post
      env:
        API_KEY: ${{ secrets.LLM_API_KEY }}
      run: |
        cd Weekly-Post
        python generate.py

    - name: Checkout jamesjb.github.io
      uses: actions/checkout@v4
      with:
        repository: clintjb/clintjb.github.io
        path: clintjb.github.io
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy generated files to website
      run: |
        mkdir -p jamesjb.github.io/images/posts/2025/
        cp Weekly-Post/input/weekly.jpg clintjb.github.io/images/posts/2025/
        cp Weekly-Post/2025-04-24-hacker-news-post.md jamesjb.github.io/_posts/2025/

    - name: Commit and push to jamesjb.github.io
      run: |
        cd clintjbjb.github.io
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Weekly LLM Blog Post Update"
        git push
